name: Documentation Improvement
description: Suggest an improvement to the project's documentation
title: "[Documentation Improvement]: "
labels: ["documentation", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement to our documentation!

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: current-documentation
    attributes:
      label: Current Documentation
      description: Describe the relevant part of the current documentation.
      placeholder: Provide a link or describe the section you want to improve.
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: Explain the improvement you are suggesting.
      placeholder: Describe the changes you'd like to see.
    validations:
      required: true

  - type: checkboxes
    id: benefits
    attributes:
      label: Benefits
      description: Check all that apply.
      options:
        - label: Clarity and Understanding
        - label: Completeness and Accuracy
        - label: Usability and User Experience
        - label: Other Benefits
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples (if applicable)
      description: If you have specific examples or code snippets to add, include them here.
      placeholder: Provide any relevant examples.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
